const products = [
  {
    name: '[Pre-order] GT-60',
    description: 'Compatible with Wooting 60HE / Venom 60HE / M61 Lite+',
    price: 159.99,
    images: ['/keyboard-1.webp'],
    brand: 'Vortexgear',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: '[Pre-order] Agar',
    description: 'Compatible with Wooting 60HE / Venom 60HE / M61 Lite+',
    price: 189.99,
    images: ['/keyboard-2.webp'],
    brand: 'Vortexgear',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Cyberboard R3',
    description: 'Aluminum CNC case with LED matrix display',
    price: 599.99,
    images: ['/keyboard-3.webp'],
    brand: 'Angry Miao',
    inStock: false,
    category: 'KEYBOARD',
  },
  {
    name: 'Keychron Q1',
    description: 'Fully customizable premium mechanical keyboard',
    price: 169.99,
    images: ['/keyboard-4.webp'],
    brand: 'Keychron',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Ducky One 3',
    description: 'TKL Hot Swappable RGB Mechanical Keyboard',
    price: 149.99,
    images: ['/keyboard-5.jpg'],
    brand: 'Ducky',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'GMMK Pro',
    description: '75% Gasket Mounted Mechanical Keyboard',
    price: 349.99,
    images: ['/keyboard-6.webp'],
    brand: 'Glorious',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Akko MOD 007',
    description: 'Gasket mount 75% keyboard kit',
    price: 159.99,
    images: ['/keyboard-7.jpg'],
    brand: 'Akko',
    inStock: false,
    category: 'KEYBOARD',
  },
  {
    name: 'NK65 Entry Edition',
    description: 'Budget-friendly 65% Keyboard',
    price: 95.0,
    images: ['/keyboard-8.jpg'],
    brand: 'NovelKeys',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Zoom65',
    description: 'Essential Edition 65% Keyboard',
    price: 179.99,
    images: ['/keyboard-9.jpg'],
    brand: 'Meletrix',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Mode Sonnet',
    description: '75% Premium Keyboard with Multiple Mounting Styles',
    price: 299.99,
    images: ['/keyboard-10.webp'],
    brand: 'Mode Designs',
    inStock: false,
    category: 'KEYBOARD',
  },
  {
    name: 'QK65',
    description: '65% keyboard with silicone and PE foam',
    price: 245.0,
    images: ['/keyboard-11.webp'],
    brand: 'QwertyKeys',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Feker IK75',
    description: 'Budget 75% keyboard with knob',
    price: 69.99,
    images: ['/keyboard-12.jpg'],
    brand: 'Feker',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Blade60',
    description: 'CNC Aluminum 60% with hidden USB port',
    price: 219.99,
    images: ['/keyboard-13.webp'],
    brand: 'KBDfans',
    inStock: false,
    category: 'KEYBOARD',
  },
  {
    name: 'Tofu84',
    description: '75% DIY Mechanical Keyboard Kit',
    price: 159.0,
    images: ['/keyboard-14.jpg'],
    brand: 'KBDfans',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'KBD67 Lite',
    description: 'Budget friendly 65% keyboard kit',
    price: 109.0,
    images: ['/keyboard-15.webp'],
    brand: 'KBDfans',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Monsgeek M1',
    description: 'Gasket mount keyboard with QMK/VIA support',
    price: 129.99,
    images: ['/keyboard-16.jpg'],
    brand: 'Monsgeek',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Vertex Angle',
    description: 'Premium TKL with unique design',
    price: 379.0,
    images: ['/keyboard-17.webp'],
    brand: 'Vertex',
    inStock: false,
    category: 'KEYBOARD',
  },
  {
    name: 'Bubble75',
    description: '75% gasket keyboard with RGB',
    price: 235.0,
    images: ['/keyboard-18.jpg'],
    brand: 'Owlab',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'KBD75 V3',
    description: 'Aluminum 75% DIY keyboard kit',
    price: 169.0,
    images: ['/keyboard-19.jpg'],
    brand: 'KBDfans',
    inStock: true,
    category: 'KEYBOARD',
  },
  {
    name: 'Freebird TKL',
    description: 'CNC aluminum TKL keyboard',
    price: 249.0,
    images: ['/keyboard-20.webp'],
    brand: 'KeebsForAll',
    inStock: false,
    category: 'KEYBOARD',
  },
];

async function seed() {
  console.log('🌱 Seeding products...');
  for (const product of products) {
    const res = await fetch('http://localhost:8081/new-product', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTdG9ybXBhdGgiLCJzdWIiOiJtc2lsdmVybWFuIiwibG9naW4iOiJ1c2VyMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTQ2Njc5NjgyMiwiZXhwIjo0NjIyNDcwNDIyfQ.GYPw7rpk1V_avr1pVmzGmWZcsI4ffLvkUgeLz9mhMBM`,
      },
      body: JSON.stringify({
        ...product,
        updatedAt: new Date().toISOString(),
      }),
    });

    if (res.ok) {
      console.log(`✅ Created: ${product.name}`);
    } else {
      console.error(`❌ Failed: ${product.name}`);
    }
  }
}

seed();
