version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testbase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testbase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis-19775.c250.eu-central-1-1.ec2.redns.redis-cloud.com
      SPRING_REDIS_PORT: 19775
      SPRING_REDIS_PASSWORD: Pe08URXWaOnTXCMew0NXPVFSr8E6NmIw
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
